language: php
sudo: true
dist: trusty
group: edge
addons:
  apt:
    sources:
    - sourceline: 'deb http://packages.erlang-solutions.com/ubuntu precise contrib'

cache:
  directories:
    - ./travisci/tmp
    - $HOME/.composer/cache

php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "hhvm-3.12"
  
jdk:
  - oraclejdk7
  
before_script:
  - sudo apt-get update
  - sudo apt-get install -y --force-yes erlang
  - phpenv config-rm xdebug.ini; true
  - ./travisci/bin/ci/setup.sh
  - composer install
  
after_script:
  - ./travisci/bin/ci/stop.sh
  - erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell